### ISSUE TITLE
Usage from the readme.md doesn't work

### ISSUE THREAD

**Issue by objque** [nuno-faria/tiler#11]
Hello, I just install all requirements into virtualenv with py3 on the board and tried to run `tiller.py` (with raw config from master branch) on the png image from the sample images dir and nothing happen:

```bash
$ mkdir result
$ virtualenv -p python3 .env
...
$ source .env/bin/activate
(.env) $ pip install -r requirements.txt
...
(.env) $ python3 tiler.py images/cake_lego.png ./result/
Loading tiles
0it [00:00, ?it/s]
Gettting and processing boxes
0it [00:00, ?it/s]
Creating tiled image
0it [00:00, ?it/s]
(.env) $ ls ./result/
(.env) $
```

what's wrong with me?

**Comment by kumardexati** [comment]
Same Issue here.

**Comment by nuno-faria** [comment]
The second argument of the tiler.py is the folder with the tiles (ex: tiles/circles/gen_circle_100/. Is the 'result' folder you provided empty? (If you want to generate tiles, use the gen_tiles.py script with an image as argument)

**Comment by objque** [comment]
I just wanna build my image with tiles, so I use `tiller.py` as said in the readme.md, is it incorrect?

**Comment by nuno-faria** [comment]
The tiler.py script is to **build** the image with the tiles. The script to **generate tiles** is the gen_tiles.py.

To generate tiles, do: `python gen_tiles.py base_image` (a folder will be created in the same directory as the base image, with a 'gen_' prefix.

To build an image from tiles, do: `python tiler.py image tiles_folder/` (the result will be in a out.png image).
