### ISSUE TITLE
only work with 'at' tiles

### ISSUE THREAD

**Issue by iwestlin** [nuno-faria/tiler#12]
<img width="708" alt="屏幕快照 2019-09-10 下午5 15 46" src="https://user-images.githubusercontent.com/6235509/64601149-01104a00-d3ef-11e9-806d-5ee4746db619.png">

second command generate empty out.png file, why?

**Comment by nuno-faria** [comment]
It was a problem with the plus tiles, since the script was not ignoring the transparent pixels (and thus the mode color was transparent). I fixed it. Now it should work.
