### ISSUE TITLE
AttributeError on tiler

### ISSUE THREAD

**Issue by joeparrie** [nuno-faria/tiler#19]
Running on VirtualBox. LinuxMint w/ Python 3.7.4

typing

`python tiler.py images/myimage.png tiles/lines/gen_line_h`

gives me the following:

`Loading tiles
100%|██████████| 125/125 [00:00<00:00, 285.37it/s]
Gettting and processing boxes
  0%|          | 0/5 [00:00<?, ?it/s]Traceback (most recent call last):
  File "tiler.py", line 223, in <module>
    main()
  File "tiler.py", line 217, in main
    boxes, original_res = get_processed_image_boxes(image_path, tiles)
  File "tiler.py", line 158, in get_processed_image_boxes
    most_similar_tiles = pool.starmap(most_similar_tile, zip(modes, [ts for x in range(len(modes))]))
AttributeError: 'Pool' object has no attribute 'starmap'
  0%|          | 0/5 [00:33<?, ?it/s]`

**Comment by nuno-faria** [comment]
Are you sure you are using Python 3 and not 2?

**Comment by joeparrie** [comment]
Turns out I was using 2.  Oops!

**Comment by joeparrie** [comment]
Worked like a charm—great work!
