### ISSUE TITLE
Creating tiles with multiple arbitrary Objects?

### ISSUE THREAD

**Issue by Schizo** [nuno-faria/tiler#20]
Just wondering whether the algorithm would still work if you use let's say paperclips and minecraft blocks, that would give a lot more creative freedom, but not sure how the algorithm would hold up with many different shapes.

**Comment by nuno-faria** [comment]
Yes! You can use any combinations of shapes you want. The script should handle it ok. The algorithm cares about matching colors, the shapes come later when its time to place the tiles in the image.

You can see in the examples the image with the cake made with clips. Multiple sizes of clips are used, and two different rotations of the same clip are used aswell.
