### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by linlin5211314** [nuno-faria/tiler#28]
Traceback (most recent call last):
  File "tiler.py", line 223, in <module>
    main()
  File "tiler.py", line 216, in main
    tiles = load_tiles(tiles_paths)
  File "tiler.py", line 85, in load_tiles
    tile = read_image(os.path.join(path, tile_name))
  File "tiler.py", line 34, in read_image
    if img.shape[2] == 3:

**Comment by nuno-faria** [comment]
Does the tiles folder provided contain only images?

**Comment by DMora92** [comment]
Have the exact same issue, this error is happening with the provided tiles folder, already tried with different default tiles folders (the ones provided on this repository) and the error still happening

**Comment by DMora92** [comment]
Found the issue! I entered the path to the folder and NOT the path to the image file! Sorry, but now you can provide a more accurate error message for this issue. 

Thanks for the app!
