### ISSUE TITLE
[Error] - Running tiler.py

### ISSUE THREAD

**Issue by lmarcelocc** [nuno-faria/tiler#29]
Hi all,

I've tried, and here's the traceback:
![image](https://user-images.githubusercontent.com/6483007/66500316-3628be80-eab9-11e9-8fa4-196ba36614e1.png)

Here' my Python version:
![image](https://user-images.githubusercontent.com/6483007/66500473-7e47e100-eab9-11e9-9848-68842eadd99d.png)

Hope it's usefull !

Thank you.

**Comment by nuno-faria** [comment]
You ran out of memory. This could happen because the image is too large or the PIXEL_SHIFT is too small. The way around this would be to run the script on a machine with higher RAM or scale down the image size / PIXEL _SHIFT.
