### ISSUE TITLE
TypeError: flip() missing 1 required positional argument: 'axis'

### ISSUE THREAD

**Issue by Clowne1** [nuno-faria/tiler#30]
WHEN I RUN :"python tiler.py images/gypsophila.png tiles/at/gen_at"  , GET:
File "tiler.py", line 188, in create_tiled_image
    place_tile(img,box)
  File "tiler.py", line 173, in place_tile
    p1 = np.flip(box['pos'])
TypeError: flip() missing 1 required positional argument: 'axis'

**Comment by Clowne1** [comment]
the problem is solved when i run p1 = np.flip(box['pos'],0)

**Comment by nuno-faria** [comment]
Are you using Python 3?

**Comment by Clowne1** [comment]
yes, i am using Python 3.7 by Anconda

发自我的iPhone


------------------ Original ------------------

**Comment by nuno-faria** [comment]
You must be using an outdated version of numpy. The current version is 1.17.0, and the `flip` method doesn't need the axis argument (see https://docs.scipy.org/doc/numpy-1.17.0/reference/generated/numpy.flip.html).

I don't use Anaconda, but running `conda update numpy` should solve your issue.
