### ISSUE TITLE
Requesting permission to use some of your Tiles

### ISSUE THREAD

**Issue by GypsyDangerous** [nuno-faria/tiler#31]
@nuno-faria  I am creating my own [tiler](https://github.com/GypsyDangerous/Image-Tiler/edit/master/readme.md) and while i have not copied any of your code I have used some of your tiles but I wanted to get permission to do this before I continue on. If you say no i will remove the tiles I have copied so far. Thanks

**Comment by nuno-faria** [comment]
You are free to use whatever files you need (including the images). The project uses the MIT licence.

Good luck on your project!

**Comment by fakefred** [comment]
So... what are the minecraft tiles licensed under? :thinking:
