### ISSUE TITLE
Config details for example output

### ISSUE THREAD

**Issue by AymanEG** [nuno-faria/tiler#32]
Hello there and thanks for this awesome repo.

I am trying to manipulate the config parameters to get the awesome results in the readme ,but I can not make that happen.

Can you provide details config for each example ?

**Comment by nuno-faria** [comment]
Basically there were two main types of configs:
- For the images with "grid" (fixed, cross stitch, minecraft, ...) I used a PIXEL_SHIFT with `None`;
- For the other type of images (circles, at, paper clips, ...) I set PIXEL_SHIFT to a fixed tuple like `(5, 5)` or `(2, 2)`;

Let me know if this solved your issue.

**Comment by AymanEG** [comment]
What about RESIZING_SCALES ? 
The default value is [0.5, 0.4, 0.3, 0.2, 0.1]

**Comment by nuno-faria** [comment]
Those should yield good results too. I might have used something like [1, 0.75, 0.5, 0.25, 0.1] for some examples. For the grid ones set to a single number, such as [0.5], in order for the algorithm to just work with one tile size.

**Comment by AymanEG** [comment]
Got it.

I runned the stary night with circle,  it took almost 3 hours to finish , but the out image is some how bugged with extra layer of brightness.

The preview through windows folder is ok
![first-result-preview](https://user-images.githubusercontent.com/23207050/74830936-e1c20500-531c-11ea-91ca-071f9cbb6128.PNG)
but when I open the image, I got this:
![first-result-out](https://user-images.githubusercontent.com/23207050/74830939-e4bcf580-531c-11ea-876b-00f74b66f4b6.png)
Run time:
![first-result](https://user-images.githubusercontent.com/23207050/74830946-e71f4f80-531c-11ea-876f-d59e8faf0ac6.PNG)

**Comment by AymanEG** [comment]
Also when I use tile folder link:
`TILES_FOLDER = "E:\\tiles\\lego"` , I got error message:
`AttributeError: 'NoneType' object has no attribute 'shape'`

So I have to choose sub folder:
`TILES_FOLDER = "E:\\tiler-master\\tiles\\lego\\gen_lego_h"`

is that normal ?

**Comment by nuno-faria** [comment]
Looks about right. The Starry Night painting is too complex to be represented by shapes with varying sizes, therefore in the provided examples I only tested with fixed tiles sizes (i.e. `PIXEL_SHIFT = None` and `RESIZING_SCALES = [0.1]`). The reason it too so long is because not only the painting has a high resolution, but also it had to test multiple sizes. Try the same config you used for the painting and apply it to the cake image, the Github logo, or a similiar "simple" one.

As for the second comment, yes. The folder with the tiles must only contain images.

**Comment by AymanEG** [comment]
Got it.

I am happy to share much better results

![starry-lego-005-001-none](https://user-images.githubusercontent.com/23207050/74833907-12a53880-5323-11ea-9322-40248ee01993.png)


![trump](https://user-images.githubusercontent.com/23207050/74833892-0c16c100-5323-11ea-9925-58d3df9969c8.png)
![trump-lego-005-001-none](https://user-images.githubusercontent.com/23207050/74833896-0d47ee00-5323-11ea-9ccc-d606633c79ee.png)


![person](https://user-images.githubusercontent.com/23207050/74834178-97905200-5323-11ea-939d-0cbd2128dfb2.PNG)
![person-lego-005-001-none](https://user-images.githubusercontent.com/23207050/74834188-9c550600-5323-11ea-9e58-38040b2cede7.png)

**Comment by nuno-faria** [comment]
Good to see! You can increase `RESIZING_SCALES`to something like `[0.25]` or a larger number if you want less detail. I'm going to close this issue since it was resolved. If you have any more questions you can keep posting them here and I will reply.
