### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by ArthKumar2511** [nuno-faria/tiler#33]
This is the error
python tiler.py
./images/logo.png ./tiles/minecraft
Loading tiles
 99%|████████████████████████████████▊| 150/151 [00:52<00:00,  2.96it/s]Traceback (most recent call last):
  File "tiler.py", line 223, in <module>
    main()
  File "tiler.py", line 216, in main
    tiles = load_tiles(tiles_paths)
  File "tiler.py", line 85, in load_tiles
    tile = read_image(os.path.join(path, tile_name))
  File "tiler.py", line 34, in read_image
    if img.shape[2] == 3:
AttributeError: 'NoneType' object has no attribute 'shape'
 99%|████████████████████████████████▊| 150/151 [00:52<00:00,  2.85it/s]

**Comment by nuno-faria** [comment]
Does the folder `./tiles/minecraft` contain only images?

**Comment by ArthKumar2511** [comment]
yes

**Comment by nuno-faria** [comment]
Add this line to the function `read_image` (line 33):  `print(path)` and check the file where it fails.

**Comment by ArthKumar2511** [comment]
It is giving me this error:
`  File "C:\Users\VVA\Videos\ForYoutube\Python\MinecraftArt\tiler\tiler.py", line 224, in <module>
    main()
  File "C:\Users\VVA\Videos\ForYoutube\Python\MinecraftArt\tiler\tiler.py", line 207, in main
    tiles_paths = conf.TILES_FOLDER.split(' ')
AttributeError: 'NoneType' object has no attribute 'split'`

**Comment by ArthKumar2511** [comment]
are you going to help?

**Comment by nuno-faria** [comment]
You didn't pass the tiles folder as argument. You either have to run `python <image_to_tile> <folder_with_tiles>` or set those variables in the `conf.py` file.

**Comment by ArthKumar2511** [comment]
i passed

**Comment by nuno-faria** [comment]
The program only uses the tiles folder from the `conf.py`file if there isn't enough arguments:
```
    if len(sys.argv) > 2:
        tiles_paths = sys.argv[2:]
    else:
        tiles_paths = conf.TILES_FOLDER.split(' ')
```

Show me the exact command you entered.

**Comment by ArthKumar2511** [comment]
I was passing 3 arugments

**Comment by ArthKumar2511** [comment]
and conf.py was corrupted, So i reinstall the package
