### ISSUE TITLE
Starting Tiler Error

### ISSUE THREAD

**Issue by RocketNinja15** [nuno-faria/tiler#34]
File "tiler.py", line 1, in <module>
    import cv2
ImportError: No module named cv2

**Comment by nuno-faria** [comment]
You have to install opencv2, among other dependencies.
You can use [`pip`](https://pip.pypa.io/en/stable/installing/) to acomplish this task: `pip install -r requirements.txt`

**Comment by RocketNinja15** [comment]
It says requirement satisfied for all three of them

**Comment by nuno-faria** [comment]
Are you using the same versions?
Run `pip --version` and `python --version` and check if they are the same. You might need to use `pip3`/`python3`.

**Comment by RocketNinja15** [comment]
pip 20.2.4 from /usr/local/lib/python3.8/site-packages/pip (python 3.8)

**Comment by nuno-faria** [comment]
What about the python one?

**Comment by RocketNinja15** [comment]
Python 2.7.16


I have python 3. Why is it using 2.7.16

**Comment by nuno-faria** [comment]
Are you using `python`or `python3`to run the commands?

**Comment by RocketNinja15** [comment]
python

**Comment by nuno-faria** [comment]
Try using `python3`.

**Comment by RocketNinja15** [comment]
is there a way i can have it default to python 3

**Comment by nuno-faria** [comment]
What OS are you using? If you using a Linux-based one you can set an [alias](https://askubuntu.com/questions/320996/how-to-make-python-program-command-execute-python-3):

**Comment by RocketNinja15** [comment]
MacOS

**Comment by nuno-faria** [comment]
You can try [this](https://stackoverflow.com/questions/18425379/how-to-set-pythons-default-version-to-3-x-on-os-x). Although I would recommend just leaving it as python3, as is common practice.

**Comment by RocketNinja15** [comment]
Last login: Mon Nov 16 12:54:36 on ttys000
xr:~ xr$ cd tiler
xr:tiler xr$ pip3 install -r requirements.txt
Collecting opencv-python
  Downloading opencv_python-4.4.0.46-cp39-cp39-macosx_10_13_x86_64.whl (52.4 MB)
     |████████████████████████████████| 52.4 MB 22 kB/s 
Collecting numpy
  Downloading numpy-1.19.4-cp39-cp39-macosx_10_9_x86_64.whl (15.4 MB)
     |████████████████████████████████| 15.4 MB 1.1 MB/s 
Collecting tqdm
  Downloading tqdm-4.52.0-py2.py3-none-any.whl (71 kB)
     |████████████████████████████████| 71 kB 2.7 MB/s 
Installing collected packages: numpy, opencv-python, tqdm
Successfully installed numpy-1.19.4 opencv-python-4.4.0.46 tqdm-4.52.0
WARNING: You are using pip version 20.2.3; however, version 20.2.4 is available.
You should consider upgrading via the '/Library/Frameworks/Python.framework/Versions/3.9/bin/python3.9 -m pip install --upgrade pip' command.
xr:tiler xr$ python tiler.py desktop/smexy tiles/tiles/minecraft
Traceback (most recent call last):
  File "tiler.py", line 1, in <module>
    import cv2
ImportError: No module named cv2
xr:tiler xr$

**Comment by nuno-faria** [comment]
You need to run the command `python3 tiler.py desktop/smexy tiles/tiles/minecraft` (replace `python`with `python3`).

**Comment by RocketNinja15** [comment]
ah ok thank you so much. it is just stuck at processing boxes

**Comment by RocketNinja15** [comment]
Gettting and processing boxes
  0%|                                                                                                         | 0/5 [00:00<?, ?it/s]

**Comment by nuno-faria** [comment]
Depending on the resolution of the image and the size of the tiling regions, it can take a while. Since you are using the minecraft tiles I recommend setting `PIXEL_SHIFT = None`, in the `conf.py` file.

**Comment by RocketNinja15** [comment]
what will that do/turn off?

**Comment by nuno-faria** [comment]
It will set the tiling region to the same size as the tiles. This means that the image will be tiled in a grid way. You can find more in the README. 
![imagem](https://user-images.githubusercontent.com/26089290/99311102-ef78cc80-2853-11eb-8894-2f6a2713baf1.png)
