### ISSUE TITLE
How do I count the number of each color block used in each picture?

### ISSUE THREAD

**Issue by contilend** [nuno-faria/tiler#39]
How do I count the number of each color block used in each picture?

**Comment by nuno-faria** [comment]
You can make the `place_tile` function return a boolean that states if a tile was placed in the image, like this:
```diff
def place_tile(img, box):
    p1 = np.flip(box['pos'])
    p2 = p1 + box['img'].shape[:2]
    img_box = img[p1[0]:p2[0], p1[1]:p2[1]]
    mask = box['tile'][:, :, 3] != 0
    mask = mask[:img_box.shape[0], :img_box.shape[1]]
    if OVERLAP_TILES or not np.any(img_box[mask]):
        img_box[mask] = box['tile'][:img_box.shape[0], :img_box.shape[1], :][mask]
+      if len(img_box[mask]) > 0:
+           return True
+   return False
```

Then you can count the number of tiles in the `create_tiled_image` function:
```diff
def create_tiled_image(boxes, res, render=False):
    print('Creating tiled image')
    img = np.zeros(shape=(res[0], res[1], 4), dtype=np.uint8)
+   n_tiles_placed = 0

    for box in tqdm(sorted(boxes, key=lambda x: x['min_dist'], reverse=OVERLAP_TILES)):
        result = place_tile(img, box)
        if render:
            show_image(img, wait=False)
            sleep(0.025)
+       if result:
+           n_tiles_placed += 1
    
+   print(f'{n_tiles_placed} tiles placed')

    return img
```

**Comment by contilend** [comment]
Thank you for your answer, but my problem is not solved, this method can only be identified using the total number of color piece, but I guess the statistics of the number of color piece of each color to use white color piece using 1000 pieces, for instance, black color piece using 200 piece, respectively the output (quantity, color piece RGB value) (1000，255，255, 255), (200,0,0,0）
，I'm sorry to have failed to make myself clear. look forward to your questions
Thank you very much！！！



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "nuno-faria/tiler"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月6日(星期一) 下午5:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [nuno-faria/tiler] How do I count the number of each color block used in each picture? (Issue #39)





 
You can make the place_tile function return a boolean that states if a tile was placed in the image, like this:
 def place_tile(img, box):     p1 = np.flip(box['pos'])     p2 = p1 + box['img'].shape[:2]     img_box = img[p1[0]:p2[0], p1[1]:p2[1]]     mask = box['tile'][:, :, 3] != 0     mask = mask[:img_box.shape[0], :img_box.shape[1]]     if OVERLAP_TILES or not np.any(img_box[mask]):         img_box[mask] = box['tile'][:img_box.shape[0], :img_box.shape[1], :][mask] +      if len(img_box[mask]) &gt; 0: +           return True +   return False
 
Then you can count the number of tiles in the create_tiled_image function:
 def create_tiled_image(boxes, res, render=False):     print('Creating tiled image')     img = np.zeros(shape=(res[0], res[1], 4), dtype=np.uint8) +   n_tiles_placed = 0     for box in tqdm(sorted(boxes, key=lambda x: x['min_dist'], reverse=OVERLAP_TILES)):         result = place_tile(img, box)         if render:             show_image(img, wait=False)             sleep(0.025) +       if result: +           n_tiles_placed += 1      +   print(f'{n_tiles_placed} tiles placed')     return img
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by nuno-faria** [comment]
I think I've got it. To find the frequency of the colors used you can add the following code:

```diff
def place_tile(img, box):
    p1 = np.flip(box['pos'])
    p2 = p1 + box['img'].shape[:2]
    img_box = img[p1[0]:p2[0], p1[1]:p2[1]]
    mask = box['tile'][:, :, 3] != 0
    mask = mask[:img_box.shape[0], :img_box.shape[1]]
    if OVERLAP_TILES or not np.any(img_box[mask]):
        img_box[mask] = box['tile'][:img_box.shape[0], :img_box.shape[1], :][mask]+
+       if len(img_box[mask]) > 0:
+           return True, mode_color(box['tile'])[0] # return the tile's mode color
+   return False, None
```

```diff
def create_tiled_image(boxes, res, render=False):
    print('Creating tiled image')
    img = np.zeros(shape=(res[0], res[1], 4), dtype=np.uint8)
+   n_tiles_placed = defaultdict(int)

    for box in tqdm(sorted(boxes, key=lambda x: x['min_dist'], reverse=OVERLAP_TILES)):
+       result, color = place_tile(img, box)
        if render:
            show_image(img, wait=False)
            sleep(0.025)
+       if result:
+           n_tiles_placed[color] += 1
+
+   for color, freq in sorted(n_tiles_placed.items(), key=lambda x: x[1], reverse=True):
+       print(f'{freq},{tuple(reversed(color))}')

    return img
```

This will print the colors and their frequency, sorted by the frequency. For example, the following image
![image](https://user-images.githubusercontent.com/26089290/145242980-0e0bb3c5-3450-416e-a307-32a750fdfb6b.png)
will have the output:
```
281,(240, 240, 180)
129,(60, 60, 60)
102,(240, 240, 240)
86,(180, 120, 60)
39,(120, 60, 60)
35,(240, 60, 60)
32,(180, 180, 180)
```

If we plot the output we get
![plot](https://user-images.githubusercontent.com/26089290/145243315-9a1e3bf6-0e31-408b-883c-e14106b853de.png)
which is consistent with the obtained image.

Keep in mind that this is based on the mode color (i.e., the most common color in the tile). Also, remember that a big tile counts just as much as a smaller one.

Let me know if this is what you wanted to achieve.

**Comment by contilend** [comment]
My problem is solved.

Yes, this is the effect I want. It turned out to be the statistics of color frequency.

This problem has bothered me for a long time, but I didn't find a solution because I always asked about the number of color patches before. Thank you for your guidance, thank you very much!!!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "nuno-faria/tiler"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月9日(星期四) 凌晨0:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [nuno-faria/tiler] How do I count the number of each color block used in each picture? (Issue #39)





 
I think I've got it. To find the frequency of the colors used you can add the following code:
 def place_tile(img, box):     p1 = np.flip(box['pos'])     p2 = p1 + box['img'].shape[:2]     img_box = img[p1[0]:p2[0], p1[1]:p2[1]]     mask = box['tile'][:, :, 3] != 0     mask = mask[:img_box.shape[0], :img_box.shape[1]]     if OVERLAP_TILES or not np.any(img_box[mask]):         img_box[mask] = box['tile'][:img_box.shape[0], :img_box.shape[1], :][mask]+ +       if len(img_box[mask]) &gt; 0: +           return True, mode_color(box['tile'])[0] # return the tile's mode color +   return False, None
 def create_tiled_image(boxes, res, render=False):     print('Creating tiled image')     img = np.zeros(shape=(res[0], res[1], 4), dtype=np.uint8) +   n_tiles_placed = defaultdict(int)     for box in tqdm(sorted(boxes, key=lambda x: x['min_dist'], reverse=OVERLAP_TILES)): +       result, color = place_tile(img, box)         if render:             show_image(img, wait=False)             sleep(0.025) +       if result: +           n_tiles_placed[color] += 1 + +   for color, freq in sorted(n_tiles_placed.items(), key=lambda x: x[1], reverse=True): +       print(f'{freq},{tuple(reversed(color))}')     return img
 
This will print the colors and their frequency, sorted by the frequency. For example, the following image
 
 will have the output:
 281,(240, 240, 180) 129,(60, 60, 60) 102,(240, 240, 240) 86,(180, 120, 60) 39,(120, 60, 60) 35,(240, 60, 60) 32,(180, 180, 180)  
If we plot the output we get
 
 which is consistent with the obtained image.
 
Keep in mind that this is based on the mode color (i.e., the most common color in the tile). Also, remember that a big tile counts just as much as a smaller one.
 
Let me know if this is what you wanted to achieve.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by contilend** [comment]
In addition, can you share the code of this visualization effect? In this regard, I am a novice and need to learn a lot. Visual display of color frequency is a good idea




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "nuno-faria/tiler"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月9日(星期四) 凌晨0:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [nuno-faria/tiler] How do I count the number of each color block used in each picture? (Issue #39)





 
I think I've got it. To find the frequency of the colors used you can add the following code:
 def place_tile(img, box):     p1 = np.flip(box['pos'])     p2 = p1 + box['img'].shape[:2]     img_box = img[p1[0]:p2[0], p1[1]:p2[1]]     mask = box['tile'][:, :, 3] != 0     mask = mask[:img_box.shape[0], :img_box.shape[1]]     if OVERLAP_TILES or not np.any(img_box[mask]):         img_box[mask] = box['tile'][:img_box.shape[0], :img_box.shape[1], :][mask]+ +       if len(img_box[mask]) &gt; 0: +           return True, mode_color(box['tile'])[0] # return the tile's mode color +   return False, None
 def create_tiled_image(boxes, res, render=False):     print('Creating tiled image')     img = np.zeros(shape=(res[0], res[1], 4), dtype=np.uint8) +   n_tiles_placed = defaultdict(int)     for box in tqdm(sorted(boxes, key=lambda x: x['min_dist'], reverse=OVERLAP_TILES)): +       result, color = place_tile(img, box)         if render:             show_image(img, wait=False)             sleep(0.025) +       if result: +           n_tiles_placed[color] += 1 + +   for color, freq in sorted(n_tiles_placed.items(), key=lambda x: x[1], reverse=True): +       print(f'{freq},{tuple(reversed(color))}')     return img
 
This will print the colors and their frequency, sorted by the frequency. For example, the following image
 
 will have the output:
 281,(240, 240, 180) 129,(60, 60, 60) 102,(240, 240, 240) 86,(180, 120, 60) 39,(120, 60, 60) 35,(240, 60, 60) 32,(180, 180, 180)  
If we plot the output we get
 
 which is consistent with the obtained image.
 
Keep in mind that this is based on the mode color (i.e., the most common color in the tile). Also, remember that a big tile counts just as much as a smaller one.
 
Let me know if this is what you wanted to achieve.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by nuno-faria** [comment]
The plot above was actually done manually using Excel, but it can be easily automated using matplotlib:

```python
import sys
import matplotlib.pyplot as plt

X = []
Y = []
colors = []

# read file and parse data
with open(sys.argv[1]) as f:
    for line in f:
        freq, color = line.split(',', 1)
        X.append(color.replace('\n', ''))
        Y.append(int(freq))
        color = color.replace('(', '').replace(')', '').split(',')
        colors.append([int(c) / 255 for c in color])

# plot data
plt.bar(X, Y, color=colors)
plt.ylabel('Number of tiles')
plt.xlabel('Color')
plt.xticks(rotation='65')
plt.title('Number of tiles per color')
plt.tight_layout()
plt.savefig('plot.png')
```

This script receives as input a file with the frequency and the colors, e.g.:
```
281,(240, 240, 180)
129,(60, 60, 60)
102,(240, 240, 240)
86,(180, 120, 60)
39,(120, 60, 60)
35,(240, 60, 60)
32,(180, 180, 180)
```

It saves the output to a file named `plot.png`:
![plot](https://user-images.githubusercontent.com/26089290/145365809-d7e1beae-a63f-4152-820b-c27fe9f33a16.png)

Glad to have helped!

**Comment by contilend** [comment]
The visualization I want has been achieved

Thank you! my friend!

Thank you very much for your patience!!!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "nuno-faria/tiler"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月9日(星期四) 下午5:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [nuno-faria/tiler] How do I count the number of each color block used in each picture? (Issue #39)





 
The plot above was actually done manually using Excel, but it can be easily automated using matplotlib:
 import sys import matplotlib.pyplot as plt X = [] Y = [] colors = [] # read file and parse data with open(sys.argv[1]) as f:     for line in f:         freq, color = line.split(',', 1)         X.append(color.replace('\n', ''))         Y.append(int(freq))         color = color.replace('(', '').replace(')', '').split(',')         colors.append([int(c) / 255 for c in color]) # plot data plt.bar(X, Y, color=colors) plt.ylabel('Number of tiles') plt.xlabel('Color') plt.xticks(rotation='65') plt.title('Number of tiles per color') plt.tight_layout() plt.savefig('plot.png')
 
This script receives as input a file with the frequency and the colors, e.g.:
 281,(240, 240, 180) 129,(60, 60, 60) 102,(240, 240, 240) 86,(180, 120, 60) 39,(120, 60, 60) 35,(240, 60, 60) 32,(180, 180, 180)  
It saves the output to a file named plot.png:
 
 
Glad to have helped!
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
