### ISSUE TITLE
conf of examples

### ISSUE THREAD

**Issue by vba34520** [nuno-faria/tiler#41]
Thank you for your job!

Could you share the different args with the examples?

Looking forward to your reply.

**Comment by nuno-faria** [comment]
Hello. I don't remember the exact configurations but here are some approximations:

If you want to build images with dynamic shapes and sizes, it is better to provide a relatively small `PIXEL_SHIFT` and multiple `RESIZING_SCALES`. 
For example, to build the cake with the dynamic circles:
```python
# config (everything else uses the default values)
RESIZING_SCALES = [1, 0.9, 0.8, 0.7, 0.6, 0.5, 0.4, 0.3, 0.2, 0.1]
PIXEL_SHIFT = (5, 5)
# command
python .\tiler.py .\cake.png .\tiles\circles\gen_circle_100\
```
![cake-circles-dynamic](https://user-images.githubusercontent.com/26089290/150348008-0f3242c5-9074-4fed-b8aa-1a899b38b7a8.png)

Or to build the cake with the paper clips:
```python
RESIZING_SCALES = [1, 0.9, 0.8, 0.7, 0.6, 0.5, 0.4, 0.3, 0.2, 0.1]
PIXEL_SHIFT = (5, 5)
python .\tiler.py .\cake.png .\tiles\clips\gen_clip\
```
![imagem](https://user-images.githubusercontent.com/26089290/150348521-ea3c9315-3b85-47c2-89ee-a7d97d1ed211.png)

If you instead want images with grid-like tiles (e.g., lego tiles), just use a single value for the `RESIZING_SCALES` and set `PIXEL_SHIFT ` to `None`.
For example, to build the cake with the fixed circles:
```python
RESIZING_SCALES = [0.1] # each circle will be 10x10, since 0.1 * 100x100 = 10x10
PIXEL_SHIFT = None # each shift will be the size of the image, i.e., 10x10
python .\tiler.py .\cake.png .\tiles\circles\gen_circle_100\
```
![imagem](https://user-images.githubusercontent.com/26089290/150349015-4c23dc6e-c69a-43d6-b1cc-1c09705c6b8f.png)

Likewise, to build the cake with a cross-stitch pattern:
```python
RESIZING_SCALES = [0.1]
PIXEL_SHIFT = None
python .\tiler.py cake.png .\tiles\times\gen_times\
```
![imagem](https://user-images.githubusercontent.com/26089290/150349040-2a270ab4-7cbd-41be-8b96-d7de45974aeb.png)

All examples provided in the README use either one or the other technique, except for the striped cake. To build that, we just need to provide small lines (`tiles/lines/gen_line_h/`) and a wide `PIXEL_SHIFT` on the x axis.
```python
RESIZING_SCALES = [0.16]
PIXEL_SHIFT = (30, 1)
python .\tiler.py cake.png .\tiles\lines\gen_line_h\
```
![imagem](https://user-images.githubusercontent.com/26089290/150349476-f00d4906-ee0f-41df-93a3-5d9f86cb97f7.png)

Hope this helps.

**Comment by vba34520** [comment]
Thank you very much for your reply, best wishes!
