### ISSUE TITLE
Error running the tiler.py

### ISSUE THREAD

**Issue by kamalhussain** [nuno-faria/tiler#6]
Get the following error. Missing anything in my usage?

`
> python tiler.py images/cake_lego.png ./tiles/clips/
Loading tiles
  0%|                                                                                                     | 0/2 [00:00<?, ?it/s]path
  0%|                                                                                                     | 0/2 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "tiler.py", line 225, in <module>
    main()
  File "tiler.py", line 218, in main
    tiles = load_tiles(tiles_paths)
  File "tiler.py", line 87, in load_tiles
    tile = read_image(path + tile_name)
  File "tiler.py", line 38, in read_image
    img = color_quantization(img.astype('float'), COLOR_DEPTH)
AttributeError: 'NoneType' object has no attribute 'astype'
`

**Comment by adkramer** [comment]
Try going down to the gen_clips directory so:
`python tiler.py ./images/cake_lego.png ./tiles/clips/gen_clip/`

**Comment by nuno-faria** [comment]
@adkramer is right. The tiles folder must have the trailing slash

**Comment by nuno-faria** [comment]
Thanks to a pull request, the trailing slash is not needed anymore.
